config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  post 'create_account', to: 'home#create_account'
  
  resources :accounts, only: [] do
    post 'deposit', to: 'accounts#deposit', on: :member, as: 'deposit'
    post 'withdraw', to: 'accounts#withdraw', on: :member, as: 'withdraw'
    post 'transfer', to: 'accounts#transfer', on: :member, as: 'transfer'
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  before_validation :init, on: :create
  
  validates :code, :balance, :user_id, presence: true

  def deposit
    @account = Account.find(params[:id])
    @account.balance = @account.balance + params[:amount].to_f
    if @account.save
      flash.now[:notice] = 'Depósito relizado com sucesso.'
    else
      flash.now[:alert] = 'Depósito não realizado'
    end
    render 'home#index'
  end

  private 
  
  def init
    self.code = SecureRandom.alphanumeric(6).upcase
    self.balance = 0
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def index
    @users = User.all
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def deposit
    account = Account.find(params[:id])
    amount = params[:amount].to_f

    account.balance = account.balance + amount
    if account.save
      return redirect_to root_path, notice: "Depósito de R$ #{amount} realizado com sucesso."
    else
      return redirect_to root_path, alert: "Depósito não realizado."
    end
  end

  def withdraw
    account = Account.find(params[:id])
    amount = params[:amount].to_f

    if amount > account.balance
      return redirect_to root_path, alert: 'Você não possui saldo disponível.'
    end
    
    account.balance = account.balance - amount
    if account.save
      return redirect_to root_path, notice: "Saque de R$ #{amount} realizado com sucesso."
    else
      return redirect_to root_path, alert: 'Saque não realizado.'
    end
  end

  def transfer
    account = Account.find(params[:id])
    amount = params[:amount].to_f

    transfer_account_code = params[:transfer_account_code]
    transfer_account = Account.where(code: transfer_account_code).first

    if !defined?(transfer_account) || !transfer_account.present?
      return redirect_to root_path, alert: "Conta com código #{transfer_account_code} não encontrada."
    end

    if amount > account.balance
      return redirect_to root_path, alert: 'Você não possui saldo disponível.'
    end
    
    account.balance = account.balance - amount
    transfer_account.balance = account.balance + amount

    if account.save && transfer_account.save
      return redirect_to root_path, notice: "Transferência de R$ #{amount} realizada com sucesso."
    else
      return redirect_to root_path, alert: 'Transferência não realizada.'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @account = Account.where(user: current_user).first
  end

  def create_account
    @account = Account.new(user: current_user)
    if @account.save()
      flash.now[:notice] = 'Conta cadastrada com sucesso.'
    else
      flash.now[:alert] = 'Conta não cadastrada'
    end
    render 'index'
  end

  def totaly_balance
    @account = Account.find(params[:id])
    params.require(:balance).permit(:balance, :deposit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<nav class="navbar navbar-expand-lg bg-light p-2 d-flex justify-content-between">
  <div>
    <% if defined?(@account) && @account.present? %>
      <div class="d-flex align-items-baseline" style="gap: .5rem;">
        <h4>Conta:</h4> 
        <span><%= @account.code %></span>
      </div>
      <div class="d-flex align-items-baseline" style="gap: .5rem;">
        <h4>Saldo:</h4> 
        <span><%= @account.balance %></span>
      </div>
    <% end %>
  </div>

  <div>
    <%= button_to 'Sair', destroy_user_session_path, method: :delete, class: "btn btn-dark" %>
  </div>
</nav>

<% if defined?(@account) && @account.present? %>
  <div class="d-flex justify-content-around" style="padding: 0 1rem;">
    <div class="card col" style="max-width: 30rem;">
      <div class="card-body">
        <h5 class="card-title">Depósito</h5>

        <%= form_tag deposit_account_path(@account.id) do %>
          <div class="input-group flex-nowrap">
            <span class="input-group-text" id="addon-wrapping">Valor</span>
            <%= number_field_tag :amount, 0, class: "form-control" %>
          </div>
          
          <%= submit_tag "Depositar", class: "btn btn-dark" %>
        <% end %>
      </div>
    </div>

    <div class="card col" style="max-width: 30rem;">
      <div class="card-body">
        <h5 class="card-title">Saque</h5>

        <%= form_tag withdraw_account_path(@account.id) do %>
          <div class="input-group flex-nowrap">
            <span class="input-group-text" id="addon-wrapping">Valor</span>
            <%= number_field_tag :amount, 0, class: "form-control" %>
          </div>

          <%= submit_tag "Sacar", class: "btn btn-dark" %>
        <% end %>
      </div>
    </div>

    <div class="card col" style="max-width: 30rem;">
      <div class="card-body">
        <h5 class="card-title">Transferência</h5>

        <%= form_tag transfer_account_path(@account.id) do %>
          <div class="input-group flex-nowrap">
            <span class="input-group-text" id="addon-wrapping">Código da conta destino</span>
            <%= text_field_tag :transfer_account_code, 'XXXXXX', class: "form-control" %>
          </div>
          
          <div class="input-group flex-nowrap">
            <span class="input-group-text" id="addon-wrapping">Valor</span>
            <%= number_field_tag :amount, 0, class: "form-control" %>
          </div>

          <%= submit_tag "Transferir", class: "btn btn-dark" %>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <%= button_to 'Abra sua conta', create_account_path %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <% if type == 'alert' %>
    <div class='alert alert-danger' >
      <%= msg %>
    </div>
  <% else %>
    <div class='alert alert-success' >
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <div class="container">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>